### PR TITLE
Lambda Terraform with Parameters, Environment and Tags

### PR DESCRIPTION
**Pull request by jams2018**
1. Install Terraform  - Link: https://www.hashicorp.com/products/terraform)
2. Install AWS Cli    - Link: https://aws.amazon.com/cli/
3. Clone the script - variables.tf & lambdacrawler.tf
4. Run these commands:
    -   aws configure        #enter your aws credentials (AWS Access Key and ID)
    -   terraform -version   #check installation
    -   terraform -init
    -   terraform -plan (If you would like to test if the code is working without creating the function)
              or
    -   terraform -apply (If you would like to create the function in AWS)

5. Check for "Apply complete!" message
6. The Lambda functions for the crawler and API are now created in your AWS acccount

Note: Please download the attached zip file and unzip the file in the same folder where you've cloned the lamdba.tf and variables.tf.

[ad440-w19-lambda-crawler-ebcrawler-79fb3944-61f5-47cd-a3cc-000ab25750e3.zip](https://github.com/ActoKids/devops/files/2939281/ad440-w19-lambda-crawler-ebcrawler-79fb3944-61f5-47cd-a3cc-000ab25750e3.zip)

Here is the command line that should be used. (Please add your access key and secret key to complete it.)

terraform apply -var region=us-east-1 -var team=crawler -var environment=dev -var runtime=python3.7 -var access_key=[enter your access key] -var secret_key=[enter your secret key] -var function_name=test1234

Expected results:
vsc_result

### CODE REVIEW

**Comment by jams2018** [comment]
The issue is fixed.

**Comment by jams2018** [comment]
#44

**Review by dashinay — APPROVED** [review]
I have run the script, terraform -plan only and it produced the expected output.

**Review by bmenaz — APPROVED** [review]
Followed the steps to run the script and got the expected outcome. Approving this pr changes into dev.

**Pull request merged**
