### PR TITLE
Ad440 w19 lambda and dynamodb crawler anar policy

### PR DESCRIPTION
**Pull request by jams2018**
Team, can you review the Lambda and Dynamodb policies for the Crawler team?

### CODE REVIEW

**Comment by amy61789** [comment]
After reviewing, cannot create an item for table - need to check policy actions:
screen shot 2019-02-20 at 12 59 42 pm

**Review by bmenaz — COMMENTED** [review]
anarpolicyreview
Overall Lambda policy is working properly by restricting the creation and deletion of functions. I had reviewed the Lambda policy using the IAM Policy Simulator. Had run the simulation with region set to us-east-1. Noticed that you had included aws:requestedregion=us-east-1 alongside restricting the region with a resource ARN, not sure if we need to have it both.

**Review by bmenaz — CHANGES_REQUESTED** [review]
anarpolicydynamodbreview
Create table and delete is restricted, however create item and delete item also not allowed. Should fix that part.

**Comment by jams2018** [comment]
The requested changes have been made.

**Review by bmenaz — APPROVED** [review]

**Comment by amy61789** [comment]
Fix was applied - can now add items to table.

**Pull request merged**
